services:
  rompetomp_inertia.inertia:
    class: Rompetomp\InertiaBundle\Service\Inertia
    public: false
    arguments:
      $engine: '@twig'
      $requestStack: '@request_stack'
      $serializer: '@?serializer'
      $package: '@?assets.packages'
  Rompetomp\InertiaBundle\Service\InertiaInterface:
    alias: rompetomp_inertia.inertia
    public: true

  rompetomp_inertia.twig_extension:
    class: Rompetomp\InertiaBundle\Twig\InertiaExtension
    public: false
    tags:
      - { name: twig.extension }

  Rompetomp\InertiaBundle\EventListener\InertiaListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request }
      - { name: kernel.event_listener, event: kernel.response }
    arguments:
      $parameterBag: '@parameter_bag'
      $inertia: '@rompetomp_inertia.inertia'
      $debug: '%kernel.debug%'
